name: CI/CD Pipeline
description: CI/CD pipeline for building, testing, and deploying a Python application with Allure reporting.

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.11.5'

          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

          - name: Run tests with Allure
            continue-on-error: true
            run: |
              pytest --alluredir=allure-results
          - name: Upload Allure results
            if: always() # Always run to upload results even if tests fail
            uses: actions/upload-artifact@v4
            with:
              name: allure
              path: allure-results
    
    allure-report:
        runs-on: ubuntu-latest
        needs: build-test
        steps:
          - name: Generate Allure report
            uses: simple-elf/allure-report-action@v1.12
            if: always() # Always run to generate report even if tests fail
            with:
                allure_results: allure-results
                allure_report: allure-report
                gh_pages: allure

          - name: Deploy report to Github Pages
            if: always()
            uses: peaceiris/actions-gh-pages@v4
            with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: allure
                publish_dir: allure-report

          - name: Publish Allure report as artifact
            if: always()
            run: echo "Allure report is available at https://tranductientdt.github.io/Demo-Selenium-Python/"
