name: 🔄 CI: Pytest + Allure Report

on:
  push:
    branches: [ main ]

jobs:
  test-and-report:
    runs-on: ubuntu-latest

    steps:
      # 👉 Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 👉 Cài Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 👉 Tạo và active virtualenv
      - name: Setup virtualenv & install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          echo ".venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV

      # 👉 Chạy pytest với Allure
      - name: Run tests with Allure
        run: |
          pytest tests/ --alluredir=allure-results -v
        continue-on-error: true

      # 👉 Checkout nhánh gh-pages để lấy history (nếu có)
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # 👉 Build Allure HTML, kết hợp history & results
      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.12
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      # 👉 Deploy lên GitHub Pages
      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
